include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - use_null_aware_elements: true
  # avoid_print: false  # Uncomment to disable the `avoid_print` rule


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
