name: moodlog
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.development
version: 1.1.1+63

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  go_router: ^16.2.4
  flutter_localizations:
    sdk: flutter
  intl: any
  collection: ^1.19.1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.40
  logging: ^1.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  table_calendar: ^3.2.0
  image_picker: ^1.2.0
  firebase_core: ^4.1.1
  firebase_ai: ^3.3.0
  firebase_analytics: ^12.0.2
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.1
  geolocator: ^14.0.1
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  path: ^1.9.1
  dotted_border: ^3.1.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  package_info_plus: ^9.0.0
  flutter_quill: ^11.4.2
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  local_auth: ^2.3.0
  flutter_screen_lock: ^9.1.2
  crypto: ^3.0.6
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.26.2
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6
  flutter_flavorizr: ^2.4.1
  mocktail: ^1.0.4


dependency_overrides:
  vector_math: 2.2.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

flutter:
  generate: true
  default-flavor: development
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/data/sample_journals_ko.json
    - assets/data/sample_journals_en.json
    - assets/data/sample_journals_ja.json
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 800
    - family: LeeSeoyun
      fonts:
        - asset: assets/fonts/LeeSeoyun-Regular.ttf
    - family: OrbitOfTheMoon
      fonts:
        - asset: assets/fonts/Nanum-OrbitOfTheMoon-Regular.ttf
    - family: Restart
      fonts:
        - asset: assets/fonts/Nanum-Restart-Regular.ttf
    - family: Overcome
      fonts:
        - asset: assets/fonts/Nanum-Overcome-Regular.ttf

