name: moodlog
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.16+44

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  collection: ^1.19.1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.34
  logging: ^1.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  table_calendar: ^3.2.0
  image_picker: ^1.1.2
  firebase_core: ^4.0.0
  firebase_ai: ^3.0.0
  firebase_auth: ^6.0.0
  firebase_analytics: ^12.0.0
  fl_chart: ^1.1.0
  flutter_svg: ^2.2.0
  google_sign_in: ^7.1.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  path: ^1.9.0
  dotted_border: ^3.1.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.25.15
  flutter_lints: ^6.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5

dependency_overrides:
  vector_math: 2.2.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 800
    - family: LeeSeoyun
      fonts:
        - asset: assets/fonts/LeeSeoyun-Regular.ttf
    - family: OrbitOfTheMoon
      fonts:
        - asset: assets/fonts/Nanum-OrbitOfTheMoon-Regular.ttf
    - family: Restart
      fonts:
        - asset: assets/fonts/Nanum-Restart-Regular.ttf
    - family: Overcome
      fonts:
        - asset: assets/fonts/Nanum-Overcome-Regular.ttf
